# Generated by Django 2.2.6 on 2020-01-04 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('comentario', models.CharField(blank=True, help_text='Introduzca aqui su comentario', max_length=300)),
                ('consumo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TestUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTest', models.CharField(max_length=30, unique=True)),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViajesEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroViajes', models.IntegerField()),
                ('distanciaMedia', models.FloatField()),
                ('nombreTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.TestUsuario')),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPersonal', models.IntegerField()),
                ('nombreTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.TestUsuario')),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneracionElectricidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadGenerada', models.FloatField()),
                ('tipo', models.CharField(help_text='(Tipo de instalaciones de generacion de electricidad)', max_length=20)),
                ('nombreTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.TestUsuario')),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoVehiculo', models.CharField(help_text='(Vehículos dedicados a transporte)', max_length=20)),
                ('kilometrosSemana', models.IntegerField()),
                ('tipoCombustible', models.CharField(help_text='(Vehículos dedicados a transporte)', max_length=20)),
                ('nombreTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.TestUsuario')),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoElectricidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwHora', models.FloatField()),
                ('nombreTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.TestUsuario')),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoEdificios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroEdificios', models.IntegerField()),
                ('tipoEdificio', models.TextField()),
                ('nombreTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.TestUsuario')),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoCalefaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='(Tipo de combustible para la calefaccion)', max_length=20)),
                ('gasto', models.FloatField()),
                ('nombreTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.TestUsuario')),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litrosAgua', models.IntegerField()),
                ('nombreTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.TestUsuario')),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
