# Generated by Django 2.2.7 on 2019-11-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('comentario', models.CharField(help_text='Introduzca aqui su comentario', max_length=300)),
                ('consumo', models.FloatField()),
            ],
        ),
    ]
