# Generated by Django 2.2.6 on 2020-01-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsumoVehículo',
            new_name='ConsumoVehiculo',
        ),
        migrations.AlterField(
            model_name='consumoagua',
            name='nombreUsuario',
            field=models.TextField(),
        ),
    ]
