# Generated by Django 2.2.6 on 2020-01-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testusuario',
            name='co2_agua',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testusuario',
            name='co2_calefaccion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testusuario',
            name='co2_edificios',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testusuario',
            name='co2_electricidad',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testusuario',
            name='co2_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testusuario',
            name='co2_vehiculo',
            field=models.FloatField(default=0),
        ),
    ]
