# Generated by Django 2.2.7 on 2019-11-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=None)),
                ('comentario', models.CharField(help_text='Introduzca aqui su comentario', max_length=300)),
                ('consumo', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
