# Generated by Django 2.2.6 on 2020-01-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testusuario',
            name='co2_agua',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testusuario',
            name='co2_calefaccion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testusuario',
            name='co2_edificios',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testusuario',
            name='co2_electricidad',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testusuario',
            name='co2_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testusuario',
            name='co2_vehiculo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='consumocalefaccion',
            name='gasto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consumocalefaccion',
            name='tipo',
            field=models.CharField(choices=[('Gas Natural', 'Gas Natural'), ('Eléctrico', 'Eléctrico'), ('Carbón', 'Carbón'), ('Gasóleo', 'Gasóleo')], default='Gas Natural', max_length=100),
        ),
        migrations.AlterField(
            model_name='consumoedificios',
            name='tipoEdificio',
            field=models.CharField(choices=[('Cemento', 'Cemento'), ('Madera', 'Madera'), ('Acero', 'Acero')], default='Cemento', max_length=100),
        ),
        migrations.AlterField(
            model_name='consumovehiculo',
            name='tipoCombustible',
            field=models.CharField(choices=[('motorGasoline', 'Gasolina'), ('diesel', 'Diesel'), ('aviationGasoline', 'aviationGasoline'), ('jetFuel', 'jetFuel')], default='Gasolina', max_length=100),
        ),
        migrations.AlterField(
            model_name='consumovehiculo',
            name='tipoVehiculo',
            field=models.CharField(choices=[('Coche', 'Coche'), ('Avión', 'Avión'), ('Autobús', 'Autobús'), ('Barco', 'Barco'), ('Tren', 'Tren')], default='Coche', max_length=100),
        ),
        migrations.AlterField(
            model_name='generacionelectricidad',
            name='tipo',
            field=models.CharField(choices=[('Paneles Solares', 'Paneles Solares'), ('Minieolica', 'Minieolica')], default='Paneles Solares', max_length=100),
        ),
        migrations.AlterField(
            model_name='viajesempresa',
            name='distanciaMedia',
            field=models.IntegerField(),
        ),
    ]
