# Generated by Django 2.2.7 on 2019-11-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191115_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
