# Generated by Django 2.2.6 on 2020-01-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200105_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumoagua',
            name='co2_agua',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='consumocalefaccion',
            name='co2_calefacion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='consumoedificios',
            name='co2_edificio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='consumoelectricidad',
            name='co2_electricidad',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='consumovehiculo',
            name='co2_vehiculo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='generacionelectricidad',
            name='co2_genElectricidad',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='personalempresa',
            name='co2_personal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='viajesempresa',
            name='co2_viajes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='consumovehiculo',
            name='tipoCombustible',
            field=models.CharField(choices=[('motorGasoline', 'Gasolina'), ('diesel', 'Diesel'), ('aviationGasoline', 'Gasolina Aviacion'), ('jetFuel', 'Jet Fuel')], default='Gasolina', max_length=100),
        ),
    ]
