# Generated by Django 2.2.7 on 2019-11-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191115_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla',
            name='comentario',
            field=models.CharField(blank=True, help_text='Introduzca aqui su comentario', max_length=300),
        ),
    ]
