# Generated by Django 3.0.2 on 2020-01-03 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191115_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('litrosAgua', models.FloatField(max_length=200)),
                ('numeroEdificios', models.IntegerField()),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FactorEmision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(max_length=35)),
                ('factor_emision', models.FloatField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
