# Generated by Django 3.0.2 on 2020-01-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_consumototal_factoremision'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoremision',
            name='unidad_fe',
            field=models.CharField(default='kgCO2/l', max_length=10),
        ),
    ]
